/**
 * pkce.ts — PKCE (RFC 7636) utility functions for the Pinac Workspace desktop auth flow.
 *
 * All functions use the Web Crypto API (crypto.subtle) — no external dependencies.
 * These run in the Tauri webview which has a full browser engine with Web Crypto.
 *
 * DO NOT import this from server-side code; crypto.subtle is a browser API.
 */

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Encodes a Uint8Array to a URL-safe Base64 string (no padding).
 * RFC 7636 §4.2: "Base64url encoding without padding".
 */
function base64UrlEncode(bytes: Uint8Array): string {
  // btoa works on binary strings; convert byte array to binary string first.
  const binary = Array.from(bytes, (b) => String.fromCharCode(b)).join("");
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a cryptographically random PKCE `code_verifier`.
 *
 * RFC 7636 §4.1: The verifier must be 43–128 characters drawn from
 * [A-Z a-z 0-9 - . _ ~].  We generate 96 random bytes → 128 base64url chars,
 * well within the allowed range.
 *
 * SECURITY: Never persist or log this value. It must be held only in memory
 * for the lifetime of a single auth flow and cleared immediately after
 * the token exchange completes or fails.
 */
export function generateCodeVerifier(): string {
  const bytes = new Uint8Array(96);
  crypto.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}

/**
 * Derives the PKCE `code_challenge` from a verifier using SHA-256.
 *
 * RFC 7636 §4.2: code_challenge = BASE64URL(SHA256(ASCII(code_verifier)))
 *
 * @param verifier — The `code_verifier` string generated by `generateCodeVerifier()`.
 * @returns A promise resolving to the base64url-encoded SHA-256 hash.
 */
export async function generateCodeChallenge(verifier: string): Promise<string> {
  const encoded = new TextEncoder().encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", encoded);
  return base64UrlEncode(new Uint8Array(digest));
}

/**
 * Generates a cryptographically random `state` parameter for CSRF protection.
 *
 * RFC 6749 §10.12: The state value must be unguessable and associated with
 * the user agent's authenticated state.  We use 32 random bytes encoded as
 * a 64-character hex string — easy to transmit as a URL param.
 */
export function generateState(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
